### ISSUE TITLE
Provide docker-compose.yml for the example test run

### ISSUE THREAD

**Issue by earthquakesan** [SANSA-Stack/Spark-RDF-Statistics#3]
The repository should provide docker-compose.yml definition for running Spark-RDF-Statistics on test data. i.e. no additional actions should be required beside `docker-compose up`.

**Comment by GezimSejdiu** [comment]
It has been integrated into [SANSA-Notebooks](https://github.com/SANSA-Stack/SANSA-Notebooks).
